# Site settings
title: babyfat的主页
email: sxcbabyfat@gamil.com
description: "Be the change you wish to see in the world. - Gandhi
              Be kind; everyone you meet is fighting a hard battle."
baseurl: ""
url: ""
weibo_username: 沈_星_尘
github_username:  babyfatty

# Build settings
markdown: kramdown
permalink: pretty
