# Site settings
title: babyfat的主页
email: sxcbabyfat@gamil.com
description: "Be the change you wish to see in the world."
baseurl: ""
url: "babyfat.github.io"
weibo_username: 沈_星_尘
github_username:  babyfatty
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: pretty
